---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bankingmobileapiversion
  labels:
    app: bankingmobileapiversion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankingmobileapiversion
  maxReplicas: 3
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
